### PR TITLE
Add version 4.0.0

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pkgw** [comment]
I've updated the patches here. These fix my local linux-64 build.

**Comment by pkgw** [comment]
@sebastian-luna-valero FWIW, if you are feeling really dedicated, you can set up a free, legal Windows VM for build testing here:

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by pkgw** [comment]
Heads up to @conda-forge/gdal that the main branch of cfitsio might be ready to bump up the 4.0.0 soon. Compatibility with older versions not clear — we're not using semver here.

**Comment by ocefpaf** [comment]
> Heads up to @conda-forge/gdal that the main branch of cfitsio might be ready to bump up the 4.0.0 soon. Compatibility with older versions not clear — we're not using semver here.

run_exports is x.x.x, so we should be OK to merge this one and gdal would pick it up in the automated migration.

**Pull request merged**
