### PR TITLE
Unvendor zlib

### PR DESCRIPTION
**Pull request by brianv0**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

zlib is currently vendored in cfitsio. This PR unvendors zlib. I have been having some issues related to the vendoring.

openSUSE (https://build.opensuse.org/package/view_file/science/cfitsio/cfitsio-zlib.patch?expand=1) and ubuntu (https://launchpadlibrarian.net/439818280/cfitsio_3.450-3_3.470-3.diff.gz) have similar patches which are appropriate for their environments.

### CODE REVIEW

**Comment by brianv0** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by teake** [comment]
Thanks for the getting the pipelines to pass @beckermr, and thanks for the contribution @brianv0! Any chance of landing this patch upstream, @brianv0?

**Comment by beckermr** [comment]
@brianv0 and I have been discussing the state of the upstream dev. Hopefully we can get something to happen, but the ball is in my court right now.

**Pull request merged**
