### PR TITLE
update to 3.420

### PR DESCRIPTION
**Pull request by dougalsutherland**

### CODE REVIEW

**Comment by dougalsutherland** [comment]
CircleCI failure is
```
checking for main in -lpthread... no
configure: error: Unable to locate pthread library needed when enabling reentrant multithreading
```
Not sure what's going on there.

**Comment by pkgw** [comment]
If you burrow down in the build log, it looks like the actual error is related to shared library paths for curl and OpenSSL. Will investigate.

**Comment by dougalsutherland** [comment]
Travis error looks like an infrastructure issue:
```
/Users/travis/build/conda-forge/cfitsio-feedstock/recipe: C2122 Found invalid license family "fitsio"
```
(But the `license` is `fitsio` and there is no `license_family`.)

Maybe something with using `conda 4.4` – @conda-forge/core? (I rerendered today....)

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-verify-feedstock/issues/6

**Comment by dougalsutherland** [comment]
Okay @pkgw, this looks ready now. :)

**Pull request merged**
