### PR TITLE
Add --enable-reentrant flag and build shared library

### PR DESCRIPTION
**Pull request by saimn**
Hi,
We have a cfitsio recipe in the [OpenAstronomy](https://github.com/OpenAstronomy/conda-channel/tree/master/recipe_templates/cfitsio) channel, and I noticed that this recipe in conda-forge was added recently. We use the conda-forge channel to build packages, so to avoid conflicts it would be easier to use your package. 
However I noticed a few differences in your recipe, so the proposed changes in this PR:
- the `--enable-reentrant` is needed for parallel programs (OpenMP).
- build also the shared library

### CODE REVIEW

**Comment by pkgw** [comment]
Thanks! This looks promising, but there seems to be a problem finding the shared library when running the tests. It would be nice to be able to work around that in a way that didn't involve manually futzing with LIBRARY_PATH environment variables.

Also, could you add the following lines to the test stanza in meta.yaml?

```
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
```

**Comment by saimn** [comment]
Not sure why but the utils binaries where linked to the shared lib. So let's try to build the shared lib later, hence the scripts should use the static lib.

**Comment by pkgw** [comment]
Cool. Looks good to merge if/when the Travis CI passes.

**Comment by saimn** [comment]
The travis build is not starting, which seems to be related to the osx_image version, but : 
- On https://travis-ci.org/conda-forge/cfitsio-feedstock there is this message : *This job was configured to run on an OS X image that was retired on January 20, 2017. New jobs will route to our Xcode 6.4 infrastructure.*
- And from https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-6.4 it seems the Xcode 6.4 image is no longer available. 
Trying with Xcode 6.4, if it doesn't work I will try the default one (xcode7.3).

**Comment by saimn** [comment]
@pkgw - Can you cancel the previous builds ?

**Comment by pkgw** [comment]
@saimn — OK, have done so.

I am not sure if the OSX image version was actually the problem. Travis CI just has enormous queues during the week so that it often take 36 hours for an OS X build to complete.

But, your change to the image is a good one. The preferred way to do this in the conda-forge framework is to run the command `conda smithy rerender` in the feedstock Git repository. This requires that you've installed the `conda-smithy` package and requires you to set up a few API keys with the CI services. If you want to run through the process, you can add the rerender to this PR; or I can do it later. I think this PR will build with the 6.4 image, but will just take a long time. The Travis queues drain significantly by Friday night so hopefully this will take less than 24 hours to process.

**Comment by saimn** [comment]
@pkgw - Ok, thanks. Let's wait for Travis then. I was not sure if it was due to a busy queue as I couldn't find it.

**Comment by pkgw** [comment]
OK, I needed to make a few tweaks, but this change is now merged via PR #3.

**Comment by saimn** [comment]
Thanks !

**Pull request merged**
